### ISSUE TITLE
(#feat): Async on advices

### ISSUE THREAD

**Issue by konstantinkrassmann** [amoilanen/jsAspect#16]
Hi again, 
In java, thats not problem, but in javascript it is. 

Imagine you want to make sure, that the user is logged in. 

``` javascript
var beforeAdvice = new jsAspect.Advice.Before(function() {
   if(!auth.isLoggedIn()){
       auth.logIn().success(function(){   //the success callback
                //tell the advice to continue           
       }).error(function(e){
              //stop and throw error        
       });
   } 
})
```

The workflow should wait until the async callback did return a response. 

A example implementation: 

``` javascript
var beforeAdvice = new jsAspect.Advice.Before(function() {
   context.isAsync = true;
   if(!auth.isLoggedIn()){
       auth.logIn().success(function(data){   //the success callback
                //tell the advice to continue
              context.promise.success();
       }).error(function(e){
              //stop and throw error
              context.promise.error(e);
       });
   }
   return context;
})
```

If you ask me, this is a really cool feature.

**Comment by amoilanen** [comment]
I would be a bit vary about this feature. We need to consider not only this particular example but the wide implications it will have for the library. Let's suppose we implement this feature:
1. If `methodA` is a synchronous method and `beforeAdviceA` is an asynchronous advice then after applying `beforeAdviceA` to `methodA`, `methodA` also becomes asynchronous. Now the code that calls `methodA` needs to change as it becomes asynchronous. In my opinion applying aspects can change the behavior of methods but not to a such extent that their signature changes (accepted arguments) or the synchronous/asynchronous behavior.
2. `methodA` is asynchronous and returns a promise,  `afterReturningA` advice is applied to `methodA`. Should `afterReturningA` be executed after the promise returned from `methodA` was completed or immediately after returning a promise?
3. What if the code to which we are applying advices uses some other asynchronous mechanism, and not ES6 promises? For example, jQuery deferreds http://api.jquery.com/category/deferred-object/ or something else like $q https://docs.angularjs.org/api/ng/service/$q? How should we interoperate with this code to ensure that the expected order of execution is preserved?

It seems that we cannot have enough control over the asynchronous execution of the client code to which we apply advices. Then the implementation details of the library can leak into the client code (example 1) or the implementation details of the client code can leak into the library (example 3). Also a number of ambiguous situations and corner cases arise (example 2), the implementation becomes more complicated.

In my opinion the library should not deal with synchronization in the client code. The task for properly handling synchronization issues and using appropriate APIs should lie entirely with the client code.

Let's return to the provided example and see what we can do about it. First, we can use an `around` advice and second we still can emulate the desired behavior given that the method to which we apply our advice already returns a promise and is asynchronous:

``` javascript
/*
 * Client code to which we apply advices.
 */
function StockQuote() {
}

StockQuote.prototype.fetch = function() {
  return new Promise(function(resolve, reject) {
    $.ajax("stockQuote")
      .done(function(quoteData) {
        resolve(quoteData);
      })
      .fail(function() {
        reject(new Error("Could not get stock data"));
      })
  });
}

/*
 * Defining advices.
 */
new jsAspect.Aspect(
  new jsAspect.Advice.Around(function(context, func) {
    new Promise(function(resolve, reject) {
      if(!auth.isLoggedIn()) {
        auth.logIn().success(function(data) {
          resolve(data);
        }).error(function(e) {
          reject(e);
        });
      } else {
        resolve();
      }
    }).then(function() {
        return func.apply(context.target, context.arguments).then(function(funcValue)) {
          resolve(funcValue);
        };
      });
    });
  })
).applyTo(StockQuote);

/*
 * Using client code.
 */
var quote = new StockQuote();

quote.fetch().then(function(quoteData) {
  showQuoteDate(quoteData);
});
```

Please, note that in the implementation of the advice we have to make assumptions about which particular promises API `fetch` is using and also that `fetch` already returns a promise. Moreover, if the method was not returning a promise like this:

``` javascript
  var quoteData = quote.fetch();
  showQuoteDate(quoteData);
```

then we would break the client code using `fetch`, because, suddenly instead of `quoteData` it would start returning a promise that resolves to `quoteData`.

**_To sum up_**:

The changes are hard to implement consistently because of the multiple mechanisms of asynchronous execution in JavaScript, make using the library error-prone and are not really needed as it is demonstrated by the last example.

The task of handling asynchronous execution lies entirely with the client code that uses the library.
